# Generated by Django 4.1.1 on 2022-09-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='products'),
        ),
    ]
