# Generated by Django 4.1.1 on 2022-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_product_category_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
