# Generated by Django 4.1.1 on 2022-09-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotuvapp', '0002_alter_order_ordered_time_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
