# Generated by Django 4.1.1 on 2022-09-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuvapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ManyToManyField(null=True, to='sotuvapp.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
