# Generated by Django 4.1.1 on 2022-09-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='jins',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ism',
            new_name='name',
        ),
    ]
